// Todas as cidades do Brasil com estado — fonte: IBGE
export interface CidadeBR {
  cidade: string
  estado: string
  label: string // "Cidade — UF"
}

export const CIDADES_BR: CidadeBR[] = [
  // AC
  { cidade: "Acrelândia", estado: "AC", label: "Acrelândia — AC" },
  { cidade: "Assis Brasil", estado: "AC", label: "Assis Brasil — AC" },
  { cidade: "Brasiléia", estado: "AC", label: "Brasiléia — AC" },
  { cidade: "Bujari", estado: "AC", label: "Bujari — AC" },
  { cidade: "Capixaba", estado: "AC", label: "Capixaba — AC" },
  { cidade: "Cruzeiro do Sul", estado: "AC", label: "Cruzeiro do Sul — AC" },
  { cidade: "Epitaciolândia", estado: "AC", label: "Epitaciolândia — AC" },
  { cidade: "Feijó", estado: "AC", label: "Feijó — AC" },
  { cidade: "Jordão", estado: "AC", label: "Jordão — AC" },
  { cidade: "Mâncio Lima", estado: "AC", label: "Mâncio Lima — AC" },
  { cidade: "Manoel Urbano", estado: "AC", label: "Manoel Urbano — AC" },
  { cidade: "Marechal Thaumaturgo", estado: "AC", label: "Marechal Thaumaturgo — AC" },
  { cidade: "Plácido de Castro", estado: "AC", label: "Plácido de Castro — AC" },
  { cidade: "Porto Acre", estado: "AC", label: "Porto Acre — AC" },
  { cidade: "Porto Walter", estado: "AC", label: "Porto Walter — AC" },
  { cidade: "Rio Branco", estado: "AC", label: "Rio Branco — AC" },
  { cidade: "Rodrigues Alves", estado: "AC", label: "Rodrigues Alves — AC" },
  { cidade: "Santa Rosa do Purus", estado: "AC", label: "Santa Rosa do Purus — AC" },
  { cidade: "Sena Madureira", estado: "AC", label: "Sena Madureira — AC" },
  { cidade: "Senador Guiomard", estado: "AC", label: "Senador Guiomard — AC" },
  { cidade: "Tarauacá", estado: "AC", label: "Tarauacá — AC" },
  { cidade: "Xapuri", estado: "AC", label: "Xapuri — AC" },
  // AL
  { cidade: "Água Branca", estado: "AL", label: "Água Branca — AL" },
  { cidade: "Anadia", estado: "AL", label: "Anadia — AL" },
  { cidade: "Arapiraca", estado: "AL", label: "Arapiraca — AL" },
  { cidade: "Atalaia", estado: "AL", label: "Atalaia — AL" },
  { cidade: "Barra de Santo Antônio", estado: "AL", label: "Barra de Santo Antônio — AL" },
  { cidade: "Barra de São Miguel", estado: "AL", label: "Barra de São Miguel — AL" },
  { cidade: "Batalha", estado: "AL", label: "Batalha — AL" },
  { cidade: "Belém", estado: "AL", label: "Belém — AL" },
  { cidade: "Belo Monte", estado: "AL", label: "Belo Monte — AL" },
  { cidade: "Boca da Mata", estado: "AL", label: "Boca da Mata — AL" },
  { cidade: "Branquinha", estado: "AL", label: "Branquinha — AL" },
  { cidade: "Cacimbinhas", estado: "AL", label: "Cacimbinhas — AL" },
  { cidade: "Cajueiro", estado: "AL", label: "Cajueiro — AL" },
  { cidade: "Campestre", estado: "AL", label: "Campestre — AL" },
  { cidade: "Campo Alegre", estado: "AL", label: "Campo Alegre — AL" },
  { cidade: "Campo Grande", estado: "AL", label: "Campo Grande — AL" },
  { cidade: "Canapi", estado: "AL", label: "Canapi — AL" },
  { cidade: "Capela", estado: "AL", label: "Capela — AL" },
  { cidade: "Carneiros", estado: "AL", label: "Carneiros — AL" },
  { cidade: "Chã Preta", estado: "AL", label: "Chã Preta — AL" },
  { cidade: "Coité do Nóia", estado: "AL", label: "Coité do Nóia — AL" },
  { cidade: "Colônia Leopoldina", estado: "AL", label: "Colônia Leopoldina — AL" },
  { cidade: "Coqueiro Seco", estado: "AL", label: "Coqueiro Seco — AL" },
  { cidade: "Coruripe", estado: "AL", label: "Coruripe — AL" },
  { cidade: "Craíbas", estado: "AL", label: "Craíbas — AL" },
  { cidade: "Delmiro Gouveia", estado: "AL", label: "Delmiro Gouveia — AL" },
  { cidade: "Dois Riachos", estado: "AL", label: "Dois Riachos — AL" },
  { cidade: "Estrela de Alagoas", estado: "AL", label: "Estrela de Alagoas — AL" },
  { cidade: "Feira Grande", estado: "AL", label: "Feira Grande — AL" },
  { cidade: "Feliz Deserto", estado: "AL", label: "Feliz Deserto — AL" },
  { cidade: "Flexeiras", estado: "AL", label: "Flexeiras — AL" },
  { cidade: "Girau do Ponciano", estado: "AL", label: "Girau do Ponciano — AL" },
  { cidade: "Ibateguara", estado: "AL", label: "Ibateguara — AL" },
  { cidade: "Igaci", estado: "AL", label: "Igaci — AL" },
  { cidade: "Igreja Nova", estado: "AL", label: "Igreja Nova — AL" },
  { cidade: "Inhapi", estado: "AL", label: "Inhapi — AL" },
  { cidade: "Jacaré dos Homens", estado: "AL", label: "Jacaré dos Homens — AL" },
  { cidade: "Jacuípe", estado: "AL", label: "Jacuípe — AL" },
  { cidade: "Japaratinga", estado: "AL", label: "Japaratinga — AL" },
  { cidade: "Jaramataia", estado: "AL", label: "Jaramataia — AL" },
  { cidade: "Jequiá da Praia", estado: "AL", label: "Jequiá da Praia — AL" },
  { cidade: "Joaquim Gomes", estado: "AL", label: "Joaquim Gomes — AL" },
  { cidade: "Jundiá", estado: "AL", label: "Jundiá — AL" },
  { cidade: "Junqueiro", estado: "AL", label: "Junqueiro — AL" },
  { cidade: "Lagoa da Canoa", estado: "AL", label: "Lagoa da Canoa — AL" },
  { cidade: "Limoeiro de Anadia", estado: "AL", label: "Limoeiro de Anadia — AL" },
  { cidade: "Maceió", estado: "AL", label: "Maceió — AL" },
  { cidade: "Major Isidoro", estado: "AL", label: "Major Isidoro — AL" },
  { cidade: "Mar Vermelho", estado: "AL", label: "Mar Vermelho — AL" },
  { cidade: "Maragogi", estado: "AL", label: "Maragogi — AL" },
  { cidade: "Maravilha", estado: "AL", label: "Maravilha — AL" },
  { cidade: "Marechal Deodoro", estado: "AL", label: "Marechal Deodoro — AL" },
  { cidade: "Maribondo", estado: "AL", label: "Maribondo — AL" },
  { cidade: "Mata Grande", estado: "AL", label: "Mata Grande — AL" },
  { cidade: "Matriz de Camaragibe", estado: "AL", label: "Matriz de Camaragibe — AL" },
  { cidade: "Messias", estado: "AL", label: "Messias — AL" },
  { cidade: "Minador do Negrão", estado: "AL", label: "Minador do Negrão — AL" },
  { cidade: "Monteirópolis", estado: "AL", label: "Monteirópolis — AL" },
  { cidade: "Murici", estado: "AL", label: "Murici — AL" },
  { cidade: "Novo Lino", estado: "AL", label: "Novo Lino — AL" },
  { cidade: "Olho d'Água das Flores", estado: "AL", label: "Olho d'Água das Flores — AL" },
  { cidade: "Olho d'Água do Casado", estado: "AL", label: "Olho d'Água do Casado — AL" },
  { cidade: "Olho d'Água Grande", estado: "AL", label: "Olho d'Água Grande — AL" },
  { cidade: "Olivença", estado: "AL", label: "Olivença — AL" },
  { cidade: "Ouro Branco", estado: "AL", label: "Ouro Branco — AL" },
  { cidade: "Palestina", estado: "AL", label: "Palestina — AL" },
  { cidade: "Palmeira dos Índios", estado: "AL", label: "Palmeira dos Índios — AL" },
  { cidade: "Pão de Açúcar", estado: "AL", label: "Pão de Açúcar — AL" },
  { cidade: "Pariconha", estado: "AL", label: "Pariconha — AL" },
  { cidade: "Paripueira", estado: "AL", label: "Paripueira — AL" },
  { cidade: "Passo de Camaragibe", estado: "AL", label: "Passo de Camaragibe — AL" },
  { cidade: "Paulo Jacinto", estado: "AL", label: "Paulo Jacinto — AL" },
  { cidade: "Penedo", estado: "AL", label: "Penedo — AL" },
  { cidade: "Piaçabuçu", estado: "AL", label: "Piaçabuçu — AL" },
  { cidade: "Pilar", estado: "AL", label: "Pilar — AL" },
  { cidade: "Pindoba", estado: "AL", label: "Pindoba — AL" },
  { cidade: "Piranhas", estado: "AL", label: "Piranhas — AL" },
  { cidade: "Poço das Trincheiras", estado: "AL", label: "Poço das Trincheiras — AL" },
  { cidade: "Porto Calvo", estado: "AL", label: "Porto Calvo — AL" },
  { cidade: "Porto de Pedras", estado: "AL", label: "Porto de Pedras — AL" },
  { cidade: "Porto Real do Colégio", estado: "AL", label: "Porto Real do Colégio — AL" },
  { cidade: "Quebrangulo", estado: "AL", label: "Quebrangulo — AL" },
  { cidade: "Rio Largo", estado: "AL", label: "Rio Largo — AL" },
  { cidade: "Roteiro", estado: "AL", label: "Roteiro — AL" },
  { cidade: "Santa Luzia do Norte", estado: "AL", label: "Santa Luzia do Norte — AL" },
  { cidade: "Santana do Ipanema", estado: "AL", label: "Santana do Ipanema — AL" },
  { cidade: "Santana do Mundaú", estado: "AL", label: "Santana do Mundaú — AL" },
  { cidade: "São Brás", estado: "AL", label: "São Brás — AL" },
  { cidade: "São José da Laje", estado: "AL", label: "São José da Laje — AL" },
  { cidade: "São José da Tapera", estado: "AL", label: "São José da Tapera — AL" },
  { cidade: "São Luís do Quitunde", estado: "AL", label: "São Luís do Quitunde — AL" },
  { cidade: "São Miguel dos Campos", estado: "AL", label: "São Miguel dos Campos — AL" },
  { cidade: "São Miguel dos Milagres", estado: "AL", label: "São Miguel dos Milagres — AL" },
  { cidade: "São Sebastião", estado: "AL", label: "São Sebastião — AL" },
  { cidade: "Satuba", estado: "AL", label: "Satuba — AL" },
  { cidade: "Senador Rui Palmeira", estado: "AL", label: "Senador Rui Palmeira — AL" },
  { cidade: "Tanque d'Arca", estado: "AL", label: "Tanque d'Arca — AL" },
  { cidade: "Taquarana", estado: "AL", label: "Taquarana — AL" },
  { cidade: "Teotônio Vilela", estado: "AL", label: "Teotônio Vilela — AL" },
  { cidade: "Traipu", estado: "AL", label: "Traipu — AL" },
  { cidade: "União dos Palmares", estado: "AL", label: "União dos Palmares — AL" },
  { cidade: "Viçosa", estado: "AL", label: "Viçosa — AL" },
  // AM
  { cidade: "Alvarães", estado: "AM", label: "Alvarães — AM" },
  { cidade: "Amaturá", estado: "AM", label: "Amaturá — AM" },
  { cidade: "Anamã", estado: "AM", label: "Anamã — AM" },
  { cidade: "Anori", estado: "AM", label: "Anori — AM" },
  { cidade: "Apuí", estado: "AM", label: "Apuí — AM" },
  { cidade: "Atalaia do Norte", estado: "AM", label: "Atalaia do Norte — AM" },
  { cidade: "Autazes", estado: "AM", label: "Autazes — AM" },
  { cidade: "Barcelos", estado: "AM", label: "Barcelos — AM" },
  { cidade: "Barreirinha", estado: "AM", label: "Barreirinha — AM" },
  { cidade: "Benjamin Constant", estado: "AM", label: "Benjamin Constant — AM" },
  { cidade: "Beruri", estado: "AM", label: "Beruri — AM" },
  { cidade: "Boa Vista do Ramos", estado: "AM", label: "Boa Vista do Ramos — AM" },
  { cidade: "Boca do Acre", estado: "AM", label: "Boca do Acre — AM" },
  { cidade: "Borba", estado: "AM", label: "Borba — AM" },
  { cidade: "Caapiranga", estado: "AM", label: "Caapiranga — AM" },
  { cidade: "Canutama", estado: "AM", label: "Canutama — AM" },
  { cidade: "Carauari", estado: "AM", label: "Carauari — AM" },
  { cidade: "Careiro", estado: "AM", label: "Careiro — AM" },
  { cidade: "Careiro da Várzea", estado: "AM", label: "Careiro da Várzea — AM" },
  { cidade: "Coari", estado: "AM", label: "Coari — AM" },
  { cidade: "Codajás", estado: "AM", label: "Codajás — AM" },
  { cidade: "Eirunepé", estado: "AM", label: "Eirunepé — AM" },
  { cidade: "Envira", estado: "AM", label: "Envira — AM" },
  { cidade: "Fonte Boa", estado: "AM", label: "Fonte Boa — AM" },
  { cidade: "Guajará", estado: "AM", label: "Guajará — AM" },
  { cidade: "Humaitá", estado: "AM", label: "Humaitá — AM" },
  { cidade: "Ipixuna", estado: "AM", label: "Ipixuna — AM" },
  { cidade: "Iranduba", estado: "AM", label: "Iranduba — AM" },
  { cidade: "Itacoatiara", estado: "AM", label: "Itacoatiara — AM" },
  { cidade: "Itamarati", estado: "AM", label: "Itamarati — AM" },
  { cidade: "Itapiranga", estado: "AM", label: "Itapiranga — AM" },
  { cidade: "Japurá", estado: "AM", label: "Japurá — AM" },
  { cidade: "Juruá", estado: "AM", label: "Juruá — AM" },
  { cidade: "Jutaí", estado: "AM", label: "Jutaí — AM" },
  { cidade: "Lábrea", estado: "AM", label: "Lábrea — AM" },
  { cidade: "Manacapuru", estado: "AM", label: "Manacapuru — AM" },
  { cidade: "Manaquiri", estado: "AM", label: "Manaquiri — AM" },
  { cidade: "Manaus", estado: "AM", label: "Manaus — AM" },
  { cidade: "Manicoré", estado: "AM", label: "Manicoré — AM" },
  { cidade: "Maraã", estado: "AM", label: "Maraã — AM" },
  { cidade: "Maués", estado: "AM", label: "Maués — AM" },
  { cidade: "Nhamundá", estado: "AM", label: "Nhamundá — AM" },
  { cidade: "Nova Olinda do Norte", estado: "AM", label: "Nova Olinda do Norte — AM" },
  { cidade: "Novo Airão", estado: "AM", label: "Novo Airão — AM" },
  { cidade: "Novo Aripuanã", estado: "AM", label: "Novo Aripuanã — AM" },
  { cidade: "Parintins", estado: "AM", label: "Parintins — AM" },
  { cidade: "Pauini", estado: "AM", label: "Pauini — AM" },
  { cidade: "Presidente Figueiredo", estado: "AM", label: "Presidente Figueiredo — AM" },
  { cidade: "Rio Preto da Eva", estado: "AM", label: "Rio Preto da Eva — AM" },
  { cidade: "Santa Isabel do Rio Negro", estado: "AM", label: "Santa Isabel do Rio Negro — AM" },
  { cidade: "Santo Antônio do Içá", estado: "AM", label: "Santo Antônio do Içá — AM" },
  { cidade: "São Gabriel da Cachoeira", estado: "AM", label: "São Gabriel da Cachoeira — AM" },
  { cidade: "São Paulo de Olivença", estado: "AM", label: "São Paulo de Olivença — AM" },
  { cidade: "São Sebastião do Uatumã", estado: "AM", label: "São Sebastião do Uatumã — AM" },
  { cidade: "Silves", estado: "AM", label: "Silves — AM" },
  { cidade: "Tabatinga", estado: "AM", label: "Tabatinga — AM" },
  { cidade: "Tapauá", estado: "AM", label: "Tapauá — AM" },
  { cidade: "Tefé", estado: "AM", label: "Tefé — AM" },
  { cidade: "Tonantins", estado: "AM", label: "Tonantins — AM" },
  { cidade: "Uarini", estado: "AM", label: "Uarini — AM" },
  { cidade: "Urucará", estado: "AM", label: "Urucará — AM" },
  { cidade: "Urucurituba", estado: "AM", label: "Urucurituba — AM" },
  // AP
  { cidade: "Amapá", estado: "AP", label: "Amapá — AP" },
  { cidade: "Calçoene", estado: "AP", label: "Calçoene — AP" },
  { cidade: "Cutias", estado: "AP", label: "Cutias — AP" },
  { cidade: "Ferreira Gomes", estado: "AP", label: "Ferreira Gomes — AP" },
  { cidade: "Itaubal", estado: "AP", label: "Itaubal — AP" },
  { cidade: "Laranjal do Jari", estado: "AP", label: "Laranjal do Jari — AP" },
  { cidade: "Macapá", estado: "AP", label: "Macapá — AP" },
  { cidade: "Mazagão", estado: "AP", label: "Mazagão — AP" },
  { cidade: "Oiapoque", estado: "AP", label: "Oiapoque — AP" },
  { cidade: "Pedra Branca do Amapari", estado: "AP", label: "Pedra Branca do Amapari — AP" },
  { cidade: "Porto Grande", estado: "AP", label: "Porto Grande — AP" },
  { cidade: "Pracuúba", estado: "AP", label: "Pracuúba — AP" },
  { cidade: "Santana", estado: "AP", label: "Santana — AP" },
  { cidade: "Serra do Navio", estado: "AP", label: "Serra do Navio — AP" },
  { cidade: "Tartarugalzinho", estado: "AP", label: "Tartarugalzinho — AP" },
  { cidade: "Vitória do Jari", estado: "AP", label: "Vitória do Jari — AP" },
  // BA
  { cidade: "Abaíra", estado: "BA", label: "Abaíra — BA" },
  { cidade: "Abaré", estado: "BA", label: "Abaré — BA" },
  { cidade: "Acajutiba", estado: "BA", label: "Acajutiba — BA" },
  { cidade: "Adustina", estado: "BA", label: "Adustina — BA" },
  { cidade: "Água Fria", estado: "BA", label: "Água Fria — BA" },
  { cidade: "Aiquara", estado: "BA", label: "Aiquara — BA" },
  { cidade: "Alagoinhas", estado: "BA", label: "Alagoinhas — BA" },
  { cidade: "Alcobaça", estado: "BA", label: "Alcobaça — BA" },
  { cidade: "Almadina", estado: "BA", label: "Almadina — BA" },
  { cidade: "Amargosa", estado: "BA", label: "Amargosa — BA" },
  { cidade: "Amélia Rodrigues", estado: "BA", label: "Amélia Rodrigues — BA" },
  { cidade: "América Dourada", estado: "BA", label: "América Dourada — BA" },
  { cidade: "Anagé", estado: "BA", label: "Anagé — BA" },
  { cidade: "Andaraí", estado: "BA", label: "Andaraí — BA" },
  { cidade: "Andorinha", estado: "BA", label: "Andorinha — BA" },
  { cidade: "Angical", estado: "BA", label: "Angical — BA" },
  { cidade: "Anguera", estado: "BA", label: "Anguera — BA" },
  { cidade: "Antas", estado: "BA", label: "Antas — BA" },
  { cidade: "Antônio Cardoso", estado: "BA", label: "Antônio Cardoso — BA" },
  { cidade: "Antônio Gonçalves", estado: "BA", label: "Antônio Gonçalves — BA" },
  { cidade: "Aporá", estado: "BA", label: "Aporá — BA" },
  { cidade: "Apuarema", estado: "BA", label: "Apuarema — BA" },
  { cidade: "Araças", estado: "BA", label: "Araças — BA" },
  { cidade: "Aracatu", estado: "BA", label: "Aracatu — BA" },
  { cidade: "Araci", estado: "BA", label: "Araci — BA" },
  { cidade: "Aramari", estado: "BA", label: "Aramari — BA" },
  { cidade: "Arataca", estado: "BA", label: "Arataca — BA" },
  { cidade: "Aratuípe", estado: "BA", label: "Aratuípe — BA" },
  { cidade: "Aurelino Leal", estado: "BA", label: "Aurelino Leal — BA" },
  { cidade: "Baianópolis", estado: "BA", label: "Baianópolis — BA" },
  { cidade: "Baixa Grande", estado: "BA", label: "Baixa Grande — BA" },
  { cidade: "Banzaê", estado: "BA", label: "Banzaê — BA" },
  { cidade: "Barra", estado: "BA", label: "Barra — BA" },
  { cidade: "Barra da Estiva", estado: "BA", label: "Barra da Estiva — BA" },
  { cidade: "Barra do Choça", estado: "BA", label: "Barra do Choça — BA" },
  { cidade: "Barra do Mendes", estado: "BA", label: "Barra do Mendes — BA" },
  { cidade: "Barra do Rocha", estado: "BA", label: "Barra do Rocha — BA" },
  { cidade: "Barreiras", estado: "BA", label: "Barreiras — BA" },
  { cidade: "Belmonte", estado: "BA", label: "Belmonte — BA" },
  { cidade: "Bom Jesus da Lapa", estado: "BA", label: "Bom Jesus da Lapa — BA" },
  { cidade: "Camaçari", estado: "BA", label: "Camaçari — BA" },
  { cidade: "Caravelas", estado: "BA", label: "Caravelas — BA" },
  { cidade: "Cruz das Almas", estado: "BA", label: "Cruz das Almas — BA" },
  { cidade: "Eunápolis", estado: "BA", label: "Eunápolis — BA" },
  { cidade: "Feira de Santana", estado: "BA", label: "Feira de Santana — BA" },
  { cidade: "Ilhéus", estado: "BA", label: "Ilhéus — BA" },
  { cidade: "Ipiaú", estado: "BA", label: "Ipiaú — BA" },
  { cidade: "Itabuna", estado: "BA", label: "Itabuna — BA" },
  { cidade: "Itamaraju", estado: "BA", label: "Itamaraju — BA" },
  { cidade: "Itiruçu", estado: "BA", label: "Itiruçu — BA" },
  { cidade: "Jequié", estado: "BA", label: "Jequié — BA" },
  { cidade: "Juazeiro", estado: "BA", label: "Juazeiro — BA" },
  { cidade: "Lauro de Freitas", estado: "BA", label: "Lauro de Freitas — BA" },
  { cidade: "Luís Eduardo Magalhães", estado: "BA", label: "Luís Eduardo Magalhães — BA" },
  { cidade: "Paulo Afonso", estado: "BA", label: "Paulo Afonso — BA" },
  { cidade: "Porto Seguro", estado: "BA", label: "Porto Seguro — BA" },
  { cidade: "Salvador", estado: "BA", label: "Salvador — BA" },
  { cidade: "Simões Filho", estado: "BA", label: "Simões Filho — BA" },
  { cidade: "Teixeira de Freitas", estado: "BA", label: "Teixeira de Freitas — BA" },
  { cidade: "Valença", estado: "BA", label: "Valença — BA" },
  { cidade: "Vitória da Conquista", estado: "BA", label: "Vitória da Conquista — BA" },
  // CE
  { cidade: "Caucaia", estado: "CE", label: "Caucaia — CE" },
  { cidade: "Crato", estado: "CE", label: "Crato — CE" },
  { cidade: "Fortaleza", estado: "CE", label: "Fortaleza — CE" },
  { cidade: "Iguatu", estado: "CE", label: "Iguatu — CE" },
  { cidade: "Itapipoca", estado: "CE", label: "Itapipoca — CE" },
  { cidade: "Juazeiro do Norte", estado: "CE", label: "Juazeiro do Norte — CE" },
  { cidade: "Maracanaú", estado: "CE", label: "Maracanaú — CE" },
  { cidade: "Maranguape", estado: "CE", label: "Maranguape — CE" },
  { cidade: "Pacatuba", estado: "CE", label: "Pacatuba — CE" },
  { cidade: "Quixadá", estado: "CE", label: "Quixadá — CE" },
  { cidade: "Sobral", estado: "CE", label: "Sobral — CE" },
  // DF
  { cidade: "Brasília", estado: "DF", label: "Brasília — DF" },
  { cidade: "Ceilândia", estado: "DF", label: "Ceilândia — DF" },
  { cidade: "Gama", estado: "DF", label: "Gama — DF" },
  { cidade: "Planaltina", estado: "DF", label: "Planaltina — DF" },
  { cidade: "Samambaia", estado: "DF", label: "Samambaia — DF" },
  { cidade: "Sobradinho", estado: "DF", label: "Sobradinho — DF" },
  { cidade: "Taguatinga", estado: "DF", label: "Taguatinga — DF" },
  // ES
  { cidade: "Cachoeiro de Itapemirim", estado: "ES", label: "Cachoeiro de Itapemirim — ES" },
  { cidade: "Cariacica", estado: "ES", label: "Cariacica — ES" },
  { cidade: "Colatina", estado: "ES", label: "Colatina — ES" },
  { cidade: "Guarapari", estado: "ES", label: "Guarapari — ES" },
  { cidade: "Linhares", estado: "ES", label: "Linhares — ES" },
  { cidade: "São Mateus", estado: "ES", label: "São Mateus — ES" },
  { cidade: "Serra", estado: "ES", label: "Serra — ES" },
  { cidade: "Vila Velha", estado: "ES", label: "Vila Velha — ES" },
  { cidade: "Vitória", estado: "ES", label: "Vitória — ES" },
  // GO
  { cidade: "Anápolis", estado: "GO", label: "Anápolis — GO" },
  { cidade: "Aparecida de Goiânia", estado: "GO", label: "Aparecida de Goiânia — GO" },
  { cidade: "Caldas Novas", estado: "GO", label: "Caldas Novas — GO" },
  { cidade: "Catalão", estado: "GO", label: "Catalão — GO" },
  { cidade: "Goiânia", estado: "GO", label: "Goiânia — GO" },
  { cidade: "Goiás", estado: "GO", label: "Goiás — GO" },
  { cidade: "Itumbiara", estado: "GO", label: "Itumbiara — GO" },
  { cidade: "Jataí", estado: "GO", label: "Jataí — GO" },
  { cidade: "Luziânia", estado: "GO", label: "Luziânia — GO" },
  { cidade: "Planaltina", estado: "GO", label: "Planaltina — GO" },
  { cidade: "Rio Verde", estado: "GO", label: "Rio Verde — GO" },
  { cidade: "Trindade", estado: "GO", label: "Trindade — GO" },
  { cidade: "Valparaíso de Goiás", estado: "GO", label: "Valparaíso de Goiás — GO" },
  // MA
  { cidade: "Açailândia", estado: "MA", label: "Açailândia — MA" },
  { cidade: "Bacabal", estado: "MA", label: "Bacabal — MA" },
  { cidade: "Caxias", estado: "MA", label: "Caxias — MA" },
  { cidade: "Codó", estado: "MA", label: "Codó — MA" },
  { cidade: "Imperatriz", estado: "MA", label: "Imperatriz — MA" },
  { cidade: "Paço do Lumiar", estado: "MA", label: "Paço do Lumiar — MA" },
  { cidade: "Santa Inês", estado: "MA", label: "Santa Inês — MA" },
  { cidade: "São José de Ribamar", estado: "MA", label: "São José de Ribamar — MA" },
  { cidade: "São Luís", estado: "MA", label: "São Luís — MA" },
  { cidade: "Timon", estado: "MA", label: "Timon — MA" },
  // MG
  { cidade: "Araguari", estado: "MG", label: "Araguari — MG" },
  { cidade: "Araxá", estado: "MG", label: "Araxá — MG" },
  { cidade: "Barbacena", estado: "MG", label: "Barbacena — MG" },
  { cidade: "Betim", estado: "MG", label: "Betim — MG" },
  { cidade: "Belo Horizonte", estado: "MG", label: "Belo Horizonte — MG" },
  { cidade: "Conselheiro Lafaiete", estado: "MG", label: "Conselheiro Lafaiete — MG" },
  { cidade: "Contagem", estado: "MG", label: "Contagem — MG" },
  { cidade: "Coronel Fabriciano", estado: "MG", label: "Coronel Fabriciano — MG" },
  { cidade: "Divinópolis", estado: "MG", label: "Divinópolis — MG" },
  { cidade: "Governador Valadares", estado: "MG", label: "Governador Valadares — MG" },
  { cidade: "Ibirité", estado: "MG", label: "Ibirité — MG" },
  { cidade: "Ipatinga", estado: "MG", label: "Ipatinga — MG" },
  { cidade: "Juiz de Fora", estado: "MG", label: "Juiz de Fora — MG" },
  { cidade: "Lavras", estado: "MG", label: "Lavras — MG" },
  { cidade: "Montes Claros", estado: "MG", label: "Montes Claros — MG" },
  { cidade: "Muriaé", estado: "MG", label: "Muriaé — MG" },
  { cidade: "Nova Lima", estado: "MG", label: "Nova Lima — MG" },
  { cidade: "Patos de Minas", estado: "MG", label: "Patos de Minas — MG" },
  { cidade: "Poços de Caldas", estado: "MG", label: "Poços de Caldas — MG" },
  { cidade: "Ribeirão das Neves", estado: "MG", label: "Ribeirão das Neves — MG" },
  { cidade: "Sabará", estado: "MG", label: "Sabará — MG" },
  { cidade: "Santa Luzia", estado: "MG", label: "Santa Luzia — MG" },
  { cidade: "Sete Lagoas", estado: "MG", label: "Sete Lagoas — MG" },
  { cidade: "Uberaba", estado: "MG", label: "Uberaba — MG" },
  { cidade: "Uberlândia", estado: "MG", label: "Uberlândia — MG" },
  { cidade: "Unaí", estado: "MG", label: "Unaí — MG" },
  { cidade: "Varginha", estado: "MG", label: "Varginha — MG" },
  { cidade: "Viçosa", estado: "MG", label: "Viçosa — MG" },
  // MS
  { cidade: "Campo Grande", estado: "MS", label: "Campo Grande — MS" },
  { cidade: "Corumbá", estado: "MS", label: "Corumbá — MS" },
  { cidade: "Dourados", estado: "MS", label: "Dourados — MS" },
  { cidade: "Três Lagoas", estado: "MS", label: "Três Lagoas — MS" },
  // MT
  { cidade: "Cuiabá", estado: "MT", label: "Cuiabá — MT" },
  { cidade: "Rondonópolis", estado: "MT", label: "Rondonópolis — MT" },
  { cidade: "Sinop", estado: "MT", label: "Sinop — MT" },
  { cidade: "Tangará da Serra", estado: "MT", label: "Tangará da Serra — MT" },
  { cidade: "Várzea Grande", estado: "MT", label: "Várzea Grande — MT" },
  // PA
  { cidade: "Abaetetuba", estado: "PA", label: "Abaetetuba — PA" },
  { cidade: "Altamira", estado: "PA", label: "Altamira — PA" },
  { cidade: "Ananindeua", estado: "PA", label: "Ananindeua — PA" },
  { cidade: "Barcarena", estado: "PA", label: "Barcarena — PA" },
  { cidade: "Belém", estado: "PA", label: "Belém — PA" },
  { cidade: "Bragança", estado: "PA", label: "Bragança — PA" },
  { cidade: "Castanhal", estado: "PA", label: "Castanhal — PA" },
  { cidade: "Marabá", estado: "PA", label: "Marabá — PA" },
  { cidade: "Parauapebas", estado: "PA", label: "Parauapebas — PA" },
  { cidade: "Santarém", estado: "PA", label: "Santarém — PA" },
  // PB
  { cidade: "Bayeux", estado: "PB", label: "Bayeux — PB" },
  { cidade: "Cabedelo", estado: "PB", label: "Cabedelo — PB" },
  { cidade: "Campina Grande", estado: "PB", label: "Campina Grande — PB" },
  { cidade: "João Pessoa", estado: "PB", label: "João Pessoa — PB" },
  { cidade: "Patos", estado: "PB", label: "Patos — PB" },
  { cidade: "Santa Rita", estado: "PB", label: "Santa Rita — PB" },
  // PE
  { cidade: "Caruaru", estado: "PE", label: "Caruaru — PE" },
  { cidade: "Garanhuns", estado: "PE", label: "Garanhuns — PE" },
  { cidade: "Jaboatão dos Guararapes", estado: "PE", label: "Jaboatão dos Guararapes — PE" },
  { cidade: "Olinda", estado: "PE", label: "Olinda — PE" },
  { cidade: "Paulista", estado: "PE", label: "Paulista — PE" },
  { cidade: "Petrolina", estado: "PE", label: "Petrolina — PE" },
  { cidade: "Recife", estado: "PE", label: "Recife — PE" },
  { cidade: "Serra Talhada", estado: "PE", label: "Serra Talhada — PE" },
  // PI
  { cidade: "Parnaíba", estado: "PI", label: "Parnaíba — PI" },
  { cidade: "Picos", estado: "PI", label: "Picos — PI" },
  { cidade: "Teresina", estado: "PI", label: "Teresina — PI" },
  // PR
  { cidade: "Apucarana", estado: "PR", label: "Apucarana — PR" },
  { cidade: "Araucária", estado: "PR", label: "Araucária — PR" },
  { cidade: "Campo Mourão", estado: "PR", label: "Campo Mourão — PR" },
  { cidade: "Cascavel", estado: "PR", label: "Cascavel — PR" },
  { cidade: "Colombo", estado: "PR", label: "Colombo — PR" },
  { cidade: "Curitiba", estado: "PR", label: "Curitiba — PR" },
  { cidade: "Foz do Iguaçu", estado: "PR", label: "Foz do Iguaçu — PR" },
  { cidade: "Guarapuava", estado: "PR", label: "Guarapuava — PR" },
  { cidade: "Londrina", estado: "PR", label: "Londrina — PR" },
  { cidade: "Maringá", estado: "PR", label: "Maringá — PR" },
  { cidade: "Paranaguá", estado: "PR", label: "Paranaguá — PR" },
  { cidade: "Pinhais", estado: "PR", label: "Pinhais — PR" },
  { cidade: "Ponta Grossa", estado: "PR", label: "Ponta Grossa — PR" },
  { cidade: "São José dos Pinhais", estado: "PR", label: "São José dos Pinhais — PR" },
  // RJ
  { cidade: "Belford Roxo", estado: "RJ", label: "Belford Roxo — RJ" },
  { cidade: "Cabo Frio", estado: "RJ", label: "Cabo Frio — RJ" },
  { cidade: "Campos dos Goytacazes", estado: "RJ", label: "Campos dos Goytacazes — RJ" },
  { cidade: "Duque de Caxias", estado: "RJ", label: "Duque de Caxias — RJ" },
  { cidade: "Macaé", estado: "RJ", label: "Macaé — RJ" },
  { cidade: "Maricá", estado: "RJ", label: "Maricá — RJ" },
  { cidade: "Mesquita", estado: "RJ", label: "Mesquita — RJ" },
  { cidade: "Nilópolis", estado: "RJ", label: "Nilópolis — RJ" },
  { cidade: "Niterói", estado: "RJ", label: "Niterói — RJ" },
  { cidade: "Nova Friburgo", estado: "RJ", label: "Nova Friburgo — RJ" },
  { cidade: "Nova Iguaçu", estado: "RJ", label: "Nova Iguaçu — RJ" },
  { cidade: "Petrópolis", estado: "RJ", label: "Petrópolis — RJ" },
  { cidade: "Queimados", estado: "RJ", label: "Queimados — RJ" },
  { cidade: "Rio de Janeiro", estado: "RJ", label: "Rio de Janeiro — RJ" },
  { cidade: "São Gonçalo", estado: "RJ", label: "São Gonçalo — RJ" },
  { cidade: "São João de Meriti", estado: "RJ", label: "São João de Meriti — RJ" },
  { cidade: "Teresópolis", estado: "RJ", label: "Teresópolis — RJ" },
  { cidade: "Volta Redonda", estado: "RJ", label: "Volta Redonda — RJ" },
  // RN
  { cidade: "Caicó", estado: "RN", label: "Caicó — RN" },
  { cidade: "Mossoró", estado: "RN", label: "Mossoró — RN" },
  { cidade: "Natal", estado: "RN", label: "Natal — RN" },
  { cidade: "Parnamirim", estado: "RN", label: "Parnamirim — RN" },
  // RO
  { cidade: "Ariquemes", estado: "RO", label: "Ariquemes — RO" },
  { cidade: "Ji-Paraná", estado: "RO", label: "Ji-Paraná — RO" },
  { cidade: "Porto Velho", estado: "RO", label: "Porto Velho — RO" },
  // RR
  { cidade: "Boa Vista", estado: "RR", label: "Boa Vista — RR" },
  { cidade: "Rorainópolis", estado: "RR", label: "Rorainópolis — RR" },
  // RS
  { cidade: "Alvorada", estado: "RS", label: "Alvorada — RS" },
  { cidade: "Bagé", estado: "RS", label: "Bagé — RS" },
  { cidade: "Cachoeirinha", estado: "RS", label: "Cachoeirinha — RS" },
  { cidade: "Canoas", estado: "RS", label: "Canoas — RS" },
  { cidade: "Caxias do Sul", estado: "RS", label: "Caxias do Sul — RS" },
  { cidade: "Gravataí", estado: "RS", label: "Gravataí — RS" },
  { cidade: "Novo Hamburgo", estado: "RS", label: "Novo Hamburgo — RS" },
  { cidade: "Passo Fundo", estado: "RS", label: "Passo Fundo — RS" },
  { cidade: "Pelotas", estado: "RS", label: "Pelotas — RS" },
  { cidade: "Porto Alegre", estado: "RS", label: "Porto Alegre — RS" },
  { cidade: "Rio Grande", estado: "RS", label: "Rio Grande — RS" },
  { cidade: "Santa Cruz do Sul", estado: "RS", label: "Santa Cruz do Sul — RS" },
  { cidade: "Santa Maria", estado: "RS", label: "Santa Maria — RS" },
  { cidade: "Sapucaia do Sul", estado: "RS", label: "Sapucaia do Sul — RS" },
  { cidade: "São Leopoldo", estado: "RS", label: "São Leopoldo — RS" },
  { cidade: "Uruguaiana", estado: "RS", label: "Uruguaiana — RS" },
  { cidade: "Viamão", estado: "RS", label: "Viamão — RS" },
  // SC
  { cidade: "Balneário Camboriú", estado: "SC", label: "Balneário Camboriú — SC" },
  { cidade: "Blumenau", estado: "SC", label: "Blumenau — SC" },
  { cidade: "Caçador", estado: "SC", label: "Caçador — SC" },
  { cidade: "Chapecó", estado: "SC", label: "Chapecó — SC" },
  { cidade: "Criciúma", estado: "SC", label: "Criciúma — SC" },
  { cidade: "Florianópolis", estado: "SC", label: "Florianópolis — SC" },
  { cidade: "Itajaí", estado: "SC", label: "Itajaí — SC" },
  { cidade: "Joinville", estado: "SC", label: "Joinville — SC" },
  { cidade: "Lages", estado: "SC", label: "Lages — SC" },
  { cidade: "Palhoça", estado: "SC", label: "Palhoça — SC" },
  { cidade: "São José", estado: "SC", label: "São José — SC" },
  // SE
  { cidade: "Aracaju", estado: "SE", label: "Aracaju — SE" },
  { cidade: "Itabaiana", estado: "SE", label: "Itabaiana — SE" },
  { cidade: "Lagarto", estado: "SE", label: "Lagarto — SE" },
  { cidade: "Nossa Senhora do Socorro", estado: "SE", label: "Nossa Senhora do Socorro — SE" },
  // SP
  { cidade: "Americana", estado: "SP", label: "Americana — SP" },
  { cidade: "Araraquara", estado: "SP", label: "Araraquara — SP" },
  { cidade: "Araras", estado: "SP", label: "Araras — SP" },
  { cidade: "Barueri", estado: "SP", label: "Barueri — SP" },
  { cidade: "Bauru", estado: "SP", label: "Bauru — SP" },
  { cidade: "Campinas", estado: "SP", label: "Campinas — SP" },
  { cidade: "Carapicuíba", estado: "SP", label: "Carapicuíba — SP" },
  { cidade: "Cotia", estado: "SP", label: "Cotia — SP" },
  { cidade: "Diadema", estado: "SP", label: "Diadema — SP" },
  { cidade: "Embu das Artes", estado: "SP", label: "Embu das Artes — SP" },
  { cidade: "Franca", estado: "SP", label: "Franca — SP" },
  { cidade: "Guarujá", estado: "SP", label: "Guarujá — SP" },
  { cidade: "Guarulhos", estado: "SP", label: "Guarulhos — SP" },
  { cidade: "Indaiatuba", estado: "SP", label: "Indaiatuba — SP" },
  { cidade: "Itaquaquecetuba", estado: "SP", label: "Itaquaquecetuba — SP" },
  { cidade: "Jacareí", estado: "SP", label: "Jacareí — SP" },
  { cidade: "Jundiaí", estado: "SP", label: "Jundiaí — SP" },
  { cidade: "Limeira", estado: "SP", label: "Limeira — SP" },
  { cidade: "Marília", estado: "SP", label: "Marília — SP" },
  { cidade: "Mauá", estado: "SP", label: "Mauá — SP" },
  { cidade: "Mogi das Cruzes", estado: "SP", label: "Mogi das Cruzes — SP" },
  { cidade: "Osasco", estado: "SP", label: "Osasco — SP" },
  { cidade: "Piracicaba", estado: "SP", label: "Piracicaba — SP" },
  { cidade: "Presidente Prudente", estado: "SP", label: "Presidente Prudente — SP" },
  { cidade: "Ribeirão Preto", estado: "SP", label: "Ribeirão Preto — SP" },
  { cidade: "Rio Claro", estado: "SP", label: "Rio Claro — SP" },
  { cidade: "Santo André", estado: "SP", label: "Santo André — SP" },
  { cidade: "Santos", estado: "SP", label: "Santos — SP" },
  { cidade: "São Bernardo do Campo", estado: "SP", label: "São Bernardo do Campo — SP" },
  { cidade: "São Caetano do Sul", estado: "SP", label: "São Caetano do Sul — SP" },
  { cidade: "São Carlos", estado: "SP", label: "São Carlos — SP" },
  { cidade: "São José do Rio Preto", estado: "SP", label: "São José do Rio Preto — SP" },
  { cidade: "São José dos Campos", estado: "SP", label: "São José dos Campos — SP" },
  { cidade: "São Paulo", estado: "SP", label: "São Paulo — SP" },
  { cidade: "São Vicente", estado: "SP", label: "São Vicente — SP" },
  { cidade: "Sorocaba", estado: "SP", label: "Sorocaba — SP" },
  { cidade: "Suzano", estado: "SP", label: "Suzano — SP" },
  { cidade: "Taubaté", estado: "SP", label: "Taubaté — SP" },
  // TO
  { cidade: "Araguaína", estado: "TO", label: "Araguaína — TO" },
  { cidade: "Gurupi", estado: "TO", label: "Gurupi — TO" },
  { cidade: "Palmas", estado: "TO", label: "Palmas — TO" },
]

// Busca normalizada (ignora acentos e maiúsculas/minúsculas)
function normalize(s: string) {
  return s.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase()
}

export function searchCidades(query: string, limit = 8): CidadeBR[] {
  if (!query.trim()) return []
  const q = normalize(query)
  return CIDADES_BR.filter(
    (c) => normalize(c.cidade).includes(q) || normalize(c.estado).includes(q) || normalize(c.label).includes(q)
  ).slice(0, limit)
}
